name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: APNA_TOKEN_YAHAN
          accountId: 17a69de882a2aa141dcb7c2e8fe22fb1
          projectName: r4x-proximity-voice
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
